name: Release
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: build mqh file
        run: .\build.ps1
        shell: pwsh
      - run: |
          ls ${{ github.workspace }}
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            MQL4BetterSyntax.mqh
          body: release note
          body_path: "CHANGELOG.md"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: latest
          name: Release ${{ steps.date.outputs.date }}
          prerelease: true
      - run: echo "ğŸ This job's status is ${{ job.status }}."
